DROP DATABASE IF EXISTS emDB;

CREATE DATABASE emDB;

USE emDB;

CREATE TABLE departments (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  name VARCHAR(25) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE roles (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  title VARCHAR(30) NULL,
  salary DECIMAL(10,2) NULL,
  department_id INT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE employees (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  first_name VARCHAR(20) NULL,
  last_name VARCHAR(20) NULL,
  role_id INT NULL,
  is_manager BOOLEAN NULL,
  manager_id INT NULL,
  PRIMARY KEY(id)
);